apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ubuntu
  template:
    metadata:
      labels:
        name: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: israphel/ubuntu-with-utils
          imagePullPolicy: Always
          command:
            - "sleep"
            - "365d"
