name: docker
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ (github.event_name != 'pull_request' && github.ref == 'main') || github.event.pull_request.head.repo.full_name == github.repository }}
          tags: israphel/${{ github.event.repository.name }}:latest
